### ISSUE TITLE
[OZ] DB Metabase

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/ozensemble#605]
- Metarialised view effectuées a la main
- Cronjob dans manifests `startups/ozensemble/apps/metabase/envs/prod/templates/refresh-view.cronjob.yaml` (https://github.com/SocialGouv/manifests/blob/master/startups/ozensemble/apps/metabase/envs/prod/templates/refresh-view.cronjob.yaml)
- ⚠ DANS ARGOCD NE PAS SYNC L'ENSEMBLE DU METABASE. IL FAUT SYNC UNIQUEMENT LE CRONJOJB !!! (le refresh peut se faire sans souci au cas ou on ne voit pas le change apres update du fichier des views)
- Liste des requetes: https://docs.google.com/spreadsheets/d/1aTxFUoI5qVdxsAcv_SJHWYp1MDdv1B2l1GmiAOHpP38/edit?gid=0#gid=0

---
- Faire le teste avec une requete donnée par Noemie
- Aller voir Nico pour lui donner une charge (en jours)
- Effectuer le reste du boulot pour toutes les requetes
- Se sync avec Noemie pour voir si tout est okay pour elle

**Comment by matmut7** [comment]
Travaux effectués sans aller dans des changements qui demanderaient trop de temps :
- ajout des annotations ingres-nginx préparées par Gary mais qui n'étaient pas appliquées sur le MB Oz
- activation du cache MB
- proposition d'utiliser des **Modèles** Metabase qui peuvent être précalculés périodiquement. Cela pourrait être une bonne alternative au materialized views sur lesquelles l'équipe produit n'a pas la main et dont elle ignore parfois même l'existence
